[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
scholarship_dao = "9ARcMm246DgL41YDQTpvwGwwF1qCsi1zHm66hzdZKSE9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
